# Generated by Django 4.2.6 on 2023-12-24 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="categoryCourse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("periods", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "timeTable",
                    models.CharField(
                        choices=[("Matutino", "Matutino"), ("Vespertino", "Vespertino"), ("Noturno", "Noturno")],
                        max_length=15,
                    ),
                ),
                ("period", models.IntegerField()),
                (
                    "acronym",
                    models.CharField(
                        error_messages={"unique": "Já existe uma turma com está abreviação"},
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="manager.categorycourse"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numberAbsents", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "commun",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                (
                    "acronym",
                    models.CharField(
                        error_messages={"unique": "Já existe uma disciplina com está abreviação"},
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="manager.teacher"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="dayClasses",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timeTable", models.CharField(max_length=15)),
                ("dayWeek", models.CharField(max_length=50)),
                ("classObj", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="manager.class")),
                (
                    "fifth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fifth",
                        to="manager.subject",
                    ),
                ),
                (
                    "first",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="first",
                        to="manager.subject",
                    ),
                ),
                (
                    "fourth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fourth",
                        to="manager.subject",
                    ),
                ),
                (
                    "second",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="second",
                        to="manager.subject",
                    ),
                ),
                (
                    "sixth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sixth",
                        to="manager.subject",
                    ),
                ),
                (
                    "third",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="third",
                        to="manager.subject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="categorycourse",
            name="coordinator",
            field=models.OneToOneField(
                error_messages={"unique": "Este professor já é coordenador de um curso"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manager.teacher",
            ),
        ),
        migrations.CreateModel(
            name="Absent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "timeTable",
                    models.CharField(
                        choices=[("Matutino", "Matutino"), ("Vespertino", "Vespertino"), ("Noturno", "Noturno")],
                        max_length=15,
                    ),
                ),
                (
                    "absentClass",
                    models.CharField(
                        choices=[("1", "1º"), ("2", "2º"), ("3", "3º"), ("4", "4º"), ("5", "5º"), ("6", "6º")],
                        max_length=15,
                    ),
                ),
                ("absentDate", models.DateField()),
                (
                    "absentTeacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="absentTeacher", to="manager.teacher"
                    ),
                ),
                ("classObj", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="manager.class")),
                (
                    "substituteTeacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substituteTeacher",
                        to="manager.teacher",
                    ),
                ),
            ],
        ),
    ]
