# Generated by Django 4.2.6 on 2023-12-29 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="manager.teacher"),
        ),
        migrations.AddField(
            model_name="manager",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="dayclasses",
            name="classObj",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="manager.class"),
        ),
        migrations.AddField(
            model_name="dayclasses",
            name="fifth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fifth",
                to="manager.subject",
            ),
        ),
        migrations.AddField(
            model_name="dayclasses",
            name="first",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="first",
                to="manager.subject",
            ),
        ),
        migrations.AddField(
            model_name="dayclasses",
            name="fourth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fourth",
                to="manager.subject",
            ),
        ),
        migrations.AddField(
            model_name="dayclasses",
            name="second",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="second",
                to="manager.subject",
            ),
        ),
        migrations.AddField(
            model_name="dayclasses",
            name="sixth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sixth",
                to="manager.subject",
            ),
        ),
        migrations.AddField(
            model_name="dayclasses",
            name="third",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="third",
                to="manager.subject",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="course",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="manager.categorycourse"),
        ),
        migrations.AddField(
            model_name="categorycourse",
            name="coordinator",
            field=models.OneToOneField(
                error_messages={"unique": "Este professor já é coordenador de um curso"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manager.teacher",
            ),
        ),
        migrations.AddField(
            model_name="absent",
            name="absentTeacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="absentTeacher", to="manager.teacher"
            ),
        ),
        migrations.AddField(
            model_name="absent",
            name="classObj",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="manager.class"),
        ),
        migrations.AddField(
            model_name="absent",
            name="substituteTeacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substituteTeacher",
                to="manager.teacher",
            ),
        ),
    ]
