# Generated by Django 4.2.6 on 2023-10-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="categoryCourse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name="teacher",
            name="imgProfile",
            field=models.ImageField(default="user-profile-icon.jpg", upload_to="UsersProfile/"),
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("acronym", models.CharField(max_length=10)),
                (
                    "course",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="manager.categorycourse"),
                ),
            ],
        ),
    ]
