# Generated by Django 4.2.6 on 2023-12-29 05:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absent",
            name="absentClass",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=15), size=None
            ),
        ),
    ]
