# Generated by Django 4.2.6 on 2023-12-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absent',
            name='absentClass',
            field=models.CharField(blank=True, choices=[('1', '1º'), ('2', '2º'), ('3', '3º'), ('4', '4º'), ('5', '5º'), ('6', '6º')], max_length=15),
        ),
    ]
