# Generated by Django 4.2.6 on 2023-10-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0003_teacher_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="numberAbsents",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
