# Generated by Django 4.2.6 on 2023-10-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0004_alter_teacher_matriculation_alter_teacher_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="period",
            field=models.CharField(
                choices=[("Matutino", "Matutino"), ("Vespertino", "Vespertino"), ("Noturno", "Noturno")],
                default="Matutino",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="dayClasses",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.CharField(max_length=50)),
                ("classObj", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="manager.class")),
                (
                    "fifth",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fifth",
                        to="manager.subject",
                    ),
                ),
                (
                    "first",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="first",
                        to="manager.subject",
                    ),
                ),
                (
                    "fourth",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fourth",
                        to="manager.subject",
                    ),
                ),
                (
                    "second",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="second",
                        to="manager.subject",
                    ),
                ),
                (
                    "sixth",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sixth",
                        to="manager.subject",
                    ),
                ),
                (
                    "third",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="third",
                        to="manager.subject",
                    ),
                ),
            ],
        ),
    ]
