# Generated by Django 4.2.6 on 2023-10-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0005_alter_class_timetable"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayclasses",
            name="timeTable",
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name="class",
            name="timeTable",
            field=models.CharField(
                choices=[("Matutino", "Matutino"), ("Vespertino", "Vespertino"), ("Noturno", "Noturno")], max_length=15
            ),
        ),
    ]
