# Generated by Django 4.2.6 on 2023-10-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0005_class_period_dayclasses"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="timeTable",
            field=models.CharField(
                choices=[("Matutino", "Matutino"), ("Vespertino", "Vespertino"), ("Noturno", "Noturno")],
                default="Matutino",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="period",
            field=models.CharField(max_length=15),
        ),
    ]
