# Generated by Django 4.2.6 on 2023-10-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0006_dayclasses_timetable_alter_class_timetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayclasses",
            name="timeTable",
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
