# Generated by Django 4.2.6 on 2023-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0006_class_timetable_alter_class_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="period",
            field=models.IntegerField(),
        ),
    ]
