# Generated by Django 4.2.6 on 2023-10-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0007_alter_dayclasses_timetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayclasses",
            name="timeTable",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
