# Generated by Django 4.2.6 on 2023-10-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0008_alter_dayclasses_timetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayclasses",
            name="timeTable",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
