# Generated by Django 4.2.6 on 2023-11-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0010_alter_dayclasses_timetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorycourse",
            name="coordinator",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="manager.teacher", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="acronym",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="acronym",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="matriculation",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="dayclasses",
            unique_together={
                ("timeTable", "day", "sixth"),
                ("timeTable", "day", "third"),
                ("timeTable", "day", "fourth"),
                ("timeTable", "day", "first"),
                ("timeTable", "day", "fifth"),
                ("timeTable", "day", "second"),
            },
        ),
    ]
