# Generated by Django 4.2.6 on 2023-11-06 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0012_alter_categorycourse_coordinator"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dayclasses",
            unique_together=set(),
        ),
    ]
