# Generated by Django 4.2.6 on 2023-11-08 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0013_alter_dayclasses_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dayclasses",
            name="day",
        ),
    ]
