# Generated by Django 4.2.6 on 2023-11-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0014_remove_dayclasses_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayclasses",
            name="day",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
