# Generated by Django 4.2.6 on 2023-11-08 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0015_dayclasses_day"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dayclasses",
            old_name="day",
            new_name="dayWeek",
        ),
    ]
