# Generated by Django 4.2.6 on 2023-11-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0016_rename_day_dayclasses_dayweek"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="acronym",
            field=models.CharField(
                error_messages={"unique": "Já existe uma turma com está abreviação"}, max_length=10, unique=True
            ),
        ),
    ]
