# Generated by Django 4.2.6 on 2023-11-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0017_alter_class_acronym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayclasses",
            name="dayWeek",
            field=models.CharField(max_length=40),
        ),
    ]
