# Generated by Django 4.2.6 on 2023-11-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_rename_imgprofile_teacher__imgprofile_and_more'),
        ('manager', '0018_alter_dayclasses_dayweek'),
    ]

    operations = [
    ]
