# Generated by Django 4.2.6 on 2023-11-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_merge_20231115_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayclasses',
            name='dayWeek',
            field=models.CharField(max_length=50),
        ),
    ]
