# Generated by Django 4.2.6 on 2023-11-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_alter_dayclasses_dayweek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='_imgProfile',
            new_name='imgProfileV',
        ),
        migrations.AlterField(
            model_name='subject',
            name='acronym',
            field=models.CharField(error_messages={'unique': 'Já existe uma disciplina com está abreviação'}, max_length=10, unique=True),
        ),
    ]
