# Generated by Django 4.2.6 on 2023-11-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_rename__imgprofile_teacher_imgprofilev_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='imgProfileV',
            new_name='imgProfileVariable',
        ),
    ]
