# Generated by Django 4.2.6 on 2023-12-08 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0008_alter_dayclasses_fifth_alter_dayclasses_first_and_more"),
        ("manager", "0024_alter_subject_teacher"),
    ]

    operations = []
