# Generated by Django 4.2.6 on 2023-12-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0025_merge_20231208_1702"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dayclasses",
            old_name="day",
            new_name="dayWeek",
        ),
        migrations.RemoveField(
            model_name="class",
            name="name",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="imgProfile",
        ),
        migrations.AddField(
            model_name="categorycourse",
            name="coordinator",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to="manager.teacher"),
        ),
        migrations.AddField(
            model_name="categorycourse",
            name="periods",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dayclasses",
            name="timeTable",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="class",
            name="acronym",
            field=models.CharField(
                error_messages={"unique": "Já existe uma turma com está abreviação"}, max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="timeTable",
            field=models.CharField(
                choices=[("Matutino", "Matutino"), ("Vespertino", "Vespertino"), ("Noturno", "Noturno")], max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="acronym",
            field=models.CharField(
                error_messages={"unique": "Já existe uma disciplina com está abreviação"}, max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="teacher",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="manager.teacher"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="matriculation",
            field=models.IntegerField(unique=True),
        ),
    ]
