# Generated by Django 4.2.6 on 2023-12-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="imgProfileVariable",
            field=models.ImageField(default="user-profile-icon.jpg", upload_to="UsersProfile/"),
        ),
        migrations.AddField(
            model_name="user",
            name="matriculation",
            field=models.IntegerField(default=1, error_messages={"unique": "Matrícula já cadastrada"}, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="telephone",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
