# Generated by Django 4.2.6 on 2023-12-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_imgprofilevariable_user_matriculation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
