# Generated by Django 4.2.6 on 2023-12-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_imgprofilevariable_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="matriculation",
            field=models.CharField(error_messages={"unique": "Matrícula já cadastrada"}, unique=True),
        ),
    ]
