# Generated by Django 4.2.6 on 2023-12-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="matriculation",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(error_messages={"unique": "Matrícula já cadastrada"}, unique=True),
        ),
    ]
