# Generated by Django 4.2.6 on 2023-12-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_user_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
